language: csharp
solution: "ci-test.sln"
dotnet: 3.0
mono: none
sudo: true
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
    - dotnet restore
script:
    - dotnet build ci-test.sln -c Release
    - dotnet test -c Release --no-build
