language: csharp
solution: "ci-test.sln"
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
mono: none
sudo: true
env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
    - sudo snap alias dotnet-sdk.dotnet dotnet
    - dotnet restore
    - dotnet build ci-test.sln -c Release
    - dotnet test -c Release --no-build
